package games.cafecito.foundry.gradle;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;
import java.util.zip.CRC32;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.TaskOutcome;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class FoundryJavaPluginTest {
    private static final String API_SHA =
            "85e91174c1a8a48629223d6459bb2ef595ad1da405b2ce88435c24fe221aec51";
    private static final String INDEX =
            "build/generated/foundryJava/assets/foundry_java/registry-index-v2.txt";
    private static final String BOOTSTRAP =
            "build/generated/foundryJava/java/"
                    + "games/cafecito/foundry/generated/FoundryGeneratedBootstrap.java";
    private static final String STARTUP_PROVIDER =
            "build/generated/foundryJava/java/"
                    + "games/cafecito/foundry/generated/FoundryGeneratedStartupProvider.java";
    private static final String STARTUP_MANIFEST =
            "build/generated/foundryJava/manifest/AndroidManifest.xml";
    private static final String CONFIGURATION =
            "build/generated/foundryJava/assets/FoundryJava.foundryextension";
    private static final byte[] BINDING_CONFIGURATION =
            """
            [configuration]
            entry_symbol = "foundry_java_library_init"
            ; exact donor bytes must survive aggregation
            """
                    .getBytes(StandardCharsets.UTF_8);

    @TempDir Path temporaryDirectory;

    @Test
    void zeroModulesProducesNoOptInMarkerOrBootstrap() throws IOException {
        Path project = project("zero", List.of());

        BuildResult result = run(project, "generateFoundryJavaRegistry");

        assertEquals(TaskOutcome.SUCCESS, result.task(":generateFoundryJavaRegistry").getOutcome());
        assertFalse(Files.exists(project.resolve(INDEX)));
        assertFalse(Files.exists(project.resolve(BOOTSTRAP)));
        assertFalse(Files.exists(project.resolve(STARTUP_PROVIDER)));
        assertFalse(Files.exists(project.resolve(STARTUP_MANIFEST)));
        assertFalse(Files.exists(project.resolve(CONFIGURATION)));
    }

    @Test
    void oneModuleProducesOneIndexAndDirectProviderBootstrap() throws IOException {
        Path alpha =
                moduleJar(
                        temporaryDirectory.resolve("alpha.jar"), "alpha", "example.AlphaRegistry");
        Path project = project("one", List.of(alpha));

        run(project, "generateFoundryJavaRegistry");

        assertEquals(
                """
                format=2
                api_sha256=%s
                generator_version=1
                runtime_contract_version=1
                bridge_contract_version=1
                module=alpha|example.AlphaRegistry
                """
                        .formatted(API_SHA),
                Files.readString(project.resolve(INDEX)));
        String bootstrap = Files.readString(project.resolve(BOOTSTRAP));
        assertTrue(bootstrap.contains("example.AlphaRegistry.PROVIDER"));
        assertTrue(
                bootstrap.contains("new games.cafecito.foundry.runtime.FoundryRegistryBootstrap"));
        assertFalse(bootstrap.contains("Class.forName"));
        assertFalse(bootstrap.contains("java.lang.reflect"));
        assertEquals(
                """
                package games.cafecito.foundry.generated;

                /** Direct pre-Activity startup provider generated by the Foundry-Java plugin. */
                public final class FoundryGeneratedStartupProvider
                        extends games.cafecito.foundry.java.FoundryJavaStartupProvider {
                    @Override
                    protected games.cafecito.foundry.runtime.FoundryRegistryBootstrap bootstrap() {
                        return FoundryGeneratedBootstrap.bootstrap();
                    }
                }
                """,
                Files.readString(project.resolve(STARTUP_PROVIDER)));
        assertEquals(
                """
                <manifest xmlns:android="http://schemas.android.com/apk/res/android">
                    <application>
                        <provider
                            android:name="${foundryJavaStartupProvider}"
                            android:authorities="${foundryJavaStartupAuthority}"
                            android:exported="false"
                            android:initOrder="100" />
                    </application>
                </manifest>
                """,
                Files.readString(project.resolve(STARTUP_MANIFEST)));
    }

    @Test
    void rejectsDescriptorPathsThatDoNotExactlyMatchTheDeclaredModule() throws IOException {
        Path nested =
                moduleJarAtPath(
                        temporaryDirectory.resolve("nested.jar"),
                        "META-INF/foundry-java/modules/nested/demo.descriptor",
                        descriptor("demo", "example.DemoRegistry"));
        Path misnamed =
                moduleJarAtPath(
                        temporaryDirectory.resolve("misnamed.jar"),
                        "META-INF/foundry-java/modules/stale.descriptor",
                        descriptor("demo", "example.DemoRegistry"));

        for (Path invalid : List.of(nested, misnamed)) {
            Path project = project(invalid.getFileName().toString() + "-project", List.of(invalid));

            BuildResult failure = runAndFail(project, "generateFoundryJavaRegistry");

            assertTrue(failure.getOutput().contains(invalid.toAbsolutePath().toString()));
            assertTrue(
                    failure.getOutput().contains("META-INF/foundry-java/modules/demo.descriptor"));
        }
    }

    @Test
    void rejectsMisnamedDescriptorInsideAnAarClassesJar() throws IOException {
        Path binding =
                bindingAarAtPath(
                        temporaryDirectory.resolve("misnamed-descriptor.aar"),
                        "META-INF/foundry-java/modules/stale.descriptor",
                        descriptor("demo", "example.DemoRegistry"),
                        List.of("x86_64"));
        Path project =
                projectWithPayloads("misnamed-aar-descriptor", List.of(binding), List.of("x86_64"));

        BuildResult failure = runAndFail(project, "generateFoundryJavaRegistry");

        assertTrue(failure.getOutput().contains(binding.toAbsolutePath().toString()));
        assertTrue(failure.getOutput().contains("classes.jar!META-INF"));
        assertTrue(failure.getOutput().contains("META-INF/foundry-java/modules/demo.descriptor"));
    }

    @Test
    void dependencyOrderCannotChangeIndexOrBootstrapBytes() throws IOException {
        Path alpha =
                moduleJar(
                        temporaryDirectory.resolve("alpha.jar"), "alpha", "example.AlphaRegistry");
        Path zeta =
                moduleJar(temporaryDirectory.resolve("zeta.jar"), "zeta", "example.ZetaRegistry");
        Path project = project("reordered", List.of(zeta, alpha));

        run(project, "generateFoundryJavaRegistry");
        byte[] firstIndex = Files.readAllBytes(project.resolve(INDEX));
        byte[] firstBootstrap = Files.readAllBytes(project.resolve(BOOTSTRAP));

        writeBuild(project, List.of(alpha, zeta));
        run(project, "generateFoundryJavaRegistry", "--rerun-tasks");

        assertArrayEquals(firstIndex, Files.readAllBytes(project.resolve(INDEX)));
        assertArrayEquals(firstBootstrap, Files.readAllBytes(project.resolve(BOOTSTRAP)));
        assertEquals(
                List.of("module=alpha|example.AlphaRegistry", "module=zeta|example.ZetaRegistry"),
                Files.readAllLines(project.resolve(INDEX)).stream()
                        .filter(line -> line.startsWith("module="))
                        .toList());
    }

    @Test
    void transitiveDependencyDescriptorsAreAggregated() throws IOException {
        Path repository = temporaryDirectory.resolve("repository");
        publishModule(repository, "leaf", "example.LeafRegistry", List.of());
        publishModule(
                repository, "root", "example.RootRegistry", List.of("games.cafecito.test:leaf:1"));
        Path project = temporaryDirectory.resolve("transitive");
        Files.createDirectories(project);
        Files.writeString(
                project.resolve("settings.gradle"),
                "pluginManagement { repositories { gradlePluginPortal() } }\n"
                        + "dependencyResolutionManagement { repositories { maven { url = uri('"
                        + repository.toUri()
                        + "') } } }\n"
                        + "rootProject.name = 'transitive'\n");
        Files.writeString(
                project.resolve("build.gradle"),
                """
                plugins {
                    id 'games.cafecito.foundry.java'
                }
                dependencies {
                    foundryJavaModules 'games.cafecito.test:root:1'
                }
                """);

        run(project, "generateFoundryJavaRegistry");

        assertEquals(
                List.of("module=leaf|example.LeafRegistry", "module=root|example.RootRegistry"),
                Files.readAllLines(project.resolve(INDEX)).stream()
                        .filter(line -> line.startsWith("module="))
                        .toList());
    }

    @Test
    void registryGenerationReusesTheConfigurationCache() throws IOException {
        Path alpha =
                moduleJar(
                        temporaryDirectory.resolve("alpha.jar"), "alpha", "example.AlphaRegistry");
        Path project = project("configuration-cache", List.of(alpha));

        run(project, "generateFoundryJavaRegistry", "--configuration-cache");
        BuildResult second = run(project, "generateFoundryJavaRegistry", "--configuration-cache");

        assertTrue(second.getOutput().contains("Reusing configuration cache."));
        assertEquals(
                TaskOutcome.UP_TO_DATE, second.task(":generateFoundryJavaRegistry").getOutcome());
    }

    @Test
    void requestedAbiValidatesTheExactBridgeAndConfigurationPayload() throws IOException {
        Path binding =
                bindingAar(
                        temporaryDirectory.resolve("binding.aar"),
                        "demo",
                        "example.DemoRegistry",
                        List.of("arm64-v8a"));
        Path project = projectWithPayloads("missing-abi", List.of(binding), List.of("x86_64"));

        BuildResult failure = runAndFail(project, "generateFoundryJavaRegistry");

        assertTrue(failure.getOutput().contains(binding.toAbsolutePath().toString()));
        assertTrue(failure.getOutput().contains("missing abi=x86_64"));
    }

    @Test
    void hostOnlyAarKeepsItsNativeRuntimeAndContributesModuleDescriptors() throws IOException {
        Path host =
                aar(
                        temporaryDirectory.resolve("foundry-host.aar"),
                        "META-INF/foundry-java/modules/host.descriptor",
                        descriptor("host", "example.HostRegistry"),
                        List.of(
                                new RawZipEntry(
                                        "jni/x86_64/libfoundry_android.so", new byte[] {1})));
        Path binding =
                bindingAar(
                        temporaryDirectory.resolve("foundry-java-binding.aar"),
                        "demo",
                        "example.DemoRegistry",
                        List.of("x86_64"));
        Path project =
                projectWithPayloads("host-and-binding", List.of(host, binding), List.of("x86_64"));

        run(project, "generateFoundryJavaRegistry");

        assertEquals(
                List.of("module=demo|example.DemoRegistry", "module=host|example.HostRegistry"),
                Files.readAllLines(project.resolve(INDEX)).stream()
                        .filter(line -> line.startsWith("module="))
                        .toList());
        assertArrayEquals(
                BINDING_CONFIGURATION, Files.readAllBytes(project.resolve(CONFIGURATION)));
        String bootstrap = Files.readString(project.resolve(BOOTSTRAP));
        assertTrue(bootstrap.contains("example.DemoRegistry.PROVIDER"));
        assertTrue(bootstrap.contains("example.HostRegistry.PROVIDER"));
    }

    @Test
    void bindingClaimantsRejectEverySortedForbiddenHostEntry() throws IOException {
        List<String> forbiddenEntries =
                List.of("jni/arm64-v8a/libfoundry_android.so", "jni/x86_64/libfoundry_android.so");
        List<List<RawZipEntry>> claimantPayloads =
                List.of(
                        List.of(
                                new RawZipEntry(
                                        "FoundryJava.foundryextension", BINDING_CONFIGURATION)),
                        List.of(new RawZipEntry("jni/x86_64/libfoundry_java.so", new byte[] {1})),
                        List.of(
                                new RawZipEntry(
                                        "FoundryJava.foundryextension", BINDING_CONFIGURATION),
                                new RawZipEntry("jni/x86_64/libfoundry_java.so", new byte[] {1})));
        for (int index = 0; index < claimantPayloads.size(); index++) {
            List<RawZipEntry> entries = new ArrayList<>(claimantPayloads.get(index));
            entries.add(new RawZipEntry("jni/x86_64/libfoundry_android.so", new byte[] {2}));
            entries.add(new RawZipEntry("jni/arm64-v8a/libfoundry_android.so", new byte[] {3}));
            Path claimant =
                    aar(
                            temporaryDirectory.resolve("claimant-" + index + ".aar"),
                            null,
                            null,
                            entries);
            Path project =
                    projectWithPayloads(
                            "forbidden-claimant-" + index, List.of(claimant), List.of("x86_64"));

            BuildResult failure = runAndFail(project, "generateFoundryJavaRegistry");

            assertTrue(failure.getOutput().contains(claimant.toAbsolutePath().toString()));
            int first = failure.getOutput().indexOf(forbiddenEntries.get(0));
            int second = failure.getOutput().indexOf(forbiddenEntries.get(1));
            assertTrue(first >= 0);
            assertTrue(second > first);
            assertFalse(Files.exists(project.resolve(INDEX)));
        }
    }

    @Test
    void duplicateBridgeAndConfigurationPayloadsFailBeforeGeneration() throws IOException {
        Path first =
                bindingAar(
                        temporaryDirectory.resolve("first.aar"),
                        "first",
                        "example.FirstRegistry",
                        List.of("x86_64"));
        Path second =
                bindingAar(
                        temporaryDirectory.resolve("second.aar"),
                        "second",
                        "example.SecondRegistry",
                        List.of("x86_64"));
        Path project =
                projectWithPayloads(
                        "duplicate-payloads", List.of(second, first), List.of("x86_64"));

        BuildResult failure = runAndFail(project, "generateFoundryJavaRegistry");

        assertTrue(failure.getOutput().contains(first.toAbsolutePath().toString()));
        assertTrue(failure.getOutput().contains(second.toAbsolutePath().toString()));
        assertTrue(failure.getOutput().contains("bridge_payload=true"));
        assertTrue(failure.getOutput().contains("configuration_payload=true"));
        assertFalse(Files.exists(project.resolve(INDEX)));
    }

    @Test
    void duplicateConfigurationEntriesInsideOneBindingFailBeforeGeneration() throws IOException {
        Path binding =
                bindingAarWithDuplicatePayload(
                        temporaryDirectory.resolve("duplicate-configuration.aar"),
                        "FoundryJava.foundryextension");
        Path project =
                projectWithPayloads(
                        "duplicate-configuration-entry", List.of(binding), List.of("x86_64"));

        BuildResult failure = runAndFail(project, "generateFoundryJavaRegistry");

        assertTrue(failure.getOutput().contains(binding.toAbsolutePath().toString()));
        assertTrue(failure.getOutput().contains("duplicate FoundryJava.foundryextension"));
        assertFalse(Files.exists(project.resolve(INDEX)));
    }

    @Test
    void duplicateBridgeEntriesInsideOneBindingFailBeforeGeneration() throws IOException {
        Path binding =
                bindingAarWithDuplicatePayload(
                        temporaryDirectory.resolve("duplicate-bridge.aar"),
                        "jni/x86_64/libfoundry_java.so");
        Path project =
                projectWithPayloads("duplicate-bridge-entry", List.of(binding), List.of("x86_64"));

        BuildResult failure = runAndFail(project, "generateFoundryJavaRegistry");

        assertTrue(failure.getOutput().contains(binding.toAbsolutePath().toString()));
        assertTrue(
                failure.getOutput()
                        .contains("duplicate bridge abi=x86_64 at jni/x86_64/libfoundry_java.so"));
        assertFalse(Files.exists(project.resolve(INDEX)));
    }

    @Test
    void androidApplicationGetsLazyVariantRegistryTasks() throws IOException {
        Path project = androidProject("variant-wiring");

        BuildResult result = run(project, "tasks", "--all");

        assertTrue(result.getOutput().contains("generateDebugFoundryJavaRegistry"));
        assertTrue(result.getOutput().contains("generateReleaseFoundryJavaRegistry"));
    }

    @Test
    void androidRuntimeGraphGeneratesVariantAssetsAndJavaForTheRequestedAbi() throws IOException {
        Path binding =
                bindingAar(
                        temporaryDirectory.resolve("android-binding.aar"),
                        "demo",
                        "example.DemoRegistry",
                        List.of("x86_64"));
        Path project = androidProject("android-runtime-graph", binding, List.of("x86_64"));

        run(project, "generateReleaseFoundryJavaRegistry");

        Path variantIndex =
                project.resolve(
                        "build/generated/assets/generateReleaseFoundryJavaRegistry/"
                                + "foundry_java/registry-index-v2.txt");
        Path variantBootstrap =
                project.resolve(
                        "build/generated/java/generateReleaseFoundryJavaRegistry/"
                                + "games/cafecito/foundry/generated/"
                                + "FoundryGeneratedBootstrap.java");
        Path variantConfiguration =
                project.resolve(
                        "build/generated/assets/generateReleaseFoundryJavaRegistry/"
                                + "FoundryJava.foundryextension");
        Path variantStartupProvider =
                project.resolve(
                        "build/generated/java/generateReleaseFoundryJavaRegistry/"
                                + "games/cafecito/foundry/generated/"
                                + "FoundryGeneratedStartupProvider.java");
        Path variantStartupManifest =
                project.resolve(
                        "build/generated/manifests/generateReleaseFoundryJavaRegistry/"
                                + "AndroidManifest.xml");
        assertTrue(Files.readString(variantIndex).contains("module=demo|example.DemoRegistry"));
        assertTrue(Files.readString(variantBootstrap).contains("example.DemoRegistry.PROVIDER"));
        assertArrayEquals(BINDING_CONFIGURATION, Files.readAllBytes(variantConfiguration));
        assertTrue(
                Files.readString(variantStartupProvider)
                        .contains("return FoundryGeneratedBootstrap.bootstrap();"));
        assertTrue(
                Files.readString(variantStartupManifest)
                        .contains(
                                "android:authorities=\"games.cafecito.test.custom."
                                        + "foundry-java-startup\""));
        assertFalse(Files.readString(variantStartupManifest).contains("${"));
    }

    @Test
    void androidBindingWithoutDescriptorsProducesNoRegistryOrConfiguration() throws IOException {
        Path binding =
                bindingAarWithoutDescriptor(
                        temporaryDirectory.resolve("binding-without-descriptors.aar"),
                        List.of("x86_64"));
        Path project = androidProject("binding-without-descriptors", binding, List.of("x86_64"));

        run(project, "generateDebugFoundryJavaRegistry");

        Path generatedAssets =
                project.resolve("build/generated/assets/generateDebugFoundryJavaRegistry");
        assertFalse(Files.exists(generatedAssets.resolve("foundry_java/registry-index-v2.txt")));
        assertFalse(Files.exists(generatedAssets.resolve("FoundryJava.foundryextension")));
        assertFalse(
                Files.exists(
                        project.resolve(
                                "build/generated/java/generateDebugFoundryJavaRegistry/"
                                        + "games/cafecito/foundry/generated/"
                                        + "FoundryGeneratedBootstrap.java")));
        assertFalse(
                Files.exists(
                        project.resolve(
                                "build/generated/java/generateDebugFoundryJavaRegistry/"
                                        + "games/cafecito/foundry/generated/"
                                        + "FoundryGeneratedStartupProvider.java")));
        assertFalse(
                Files.exists(
                        project.resolve(
                                "build/generated/manifests/generateDebugFoundryJavaRegistry/"
                                        + "AndroidManifest.xml")));
    }

    @Test
    void androidApplicationRejectsAnEmptyRequestedAbiSetBeforeGeneratingOutputs()
            throws IOException {
        Path binding =
                bindingAar(
                        temporaryDirectory.resolve("empty-requested-abis.aar"),
                        "demo",
                        "example.DemoRegistry",
                        List.of("arm64-v8a", "x86_64"));
        Path project = androidProject("empty-requested-abis", binding, List.of());

        BuildResult failure = runAndFail(project, "generateReleaseFoundryJavaRegistry");

        assertTrue(
                failure.getOutput()
                        .contains("requested_abis must contain at least one Android ABI"));
        assertTrue(failure.getOutput().contains(binding.toAbsolutePath().toString()));
        assertFalse(
                Files.exists(
                        project.resolve(
                                "build/generated/assets/generateReleaseFoundryJavaRegistry/"
                                        + "foundry_java/registry-index-v2.txt")));
        assertFalse(
                Files.exists(
                        project.resolve(
                                "build/generated/java/generateReleaseFoundryJavaRegistry/"
                                        + "games/cafecito/foundry/generated/"
                                        + "FoundryGeneratedBootstrap.java")));
    }

    @Test
    void minifiedReleasePackagesOneIndexConfigAndSelectedAbiWithCustomApplicationId()
            throws IOException {
        Path host =
                aar(
                        temporaryDirectory.resolve("minified-host.aar"),
                        null,
                        null,
                        List.of(
                                new RawZipEntry(
                                        "jni/x86_64/libfoundry_android.so", new byte[] {1})));
        Path binding =
                bindingAar(
                        temporaryDirectory.resolve("minified-binding.aar"),
                        "demo",
                        "example.DemoRegistry",
                        List.of("arm64-v8a", "x86_64"));
        Path project =
                androidProject("minified-release", List.of(host, binding), List.of("x86_64"));
        writeBootstrapStubs(project);

        run(project, "assembleRelease", "--configuration-cache");
        BuildResult second = run(project, "assembleRelease", "--configuration-cache");

        assertTrue(second.getOutput().contains("Reusing configuration cache."));
        Path apk =
                Files.list(project.resolve("build/outputs/apk/release"))
                        .filter(path -> path.getFileName().toString().endsWith(".apk"))
                        .findFirst()
                        .orElseThrow();
        try (java.util.zip.ZipFile archive = new java.util.zip.ZipFile(apk.toFile())) {
            assertEquals(
                    1,
                    archive.stream()
                            .filter(
                                    entry ->
                                            entry.getName()
                                                    .equals(
                                                            "assets/foundry_java/"
                                                                    + "registry-index-v2.txt"))
                            .count());
            assertEquals(
                    List.of("assets/FoundryJava.foundryextension"),
                    archive.stream()
                            .map(ZipEntry::getName)
                            .filter(name -> name.endsWith("FoundryJava.foundryextension"))
                            .toList());
            assertArrayEquals(
                    BINDING_CONFIGURATION,
                    archive.getInputStream(archive.getEntry("assets/FoundryJava.foundryextension"))
                            .readAllBytes());
            assertTrue(archive.getEntry("lib/x86_64/libfoundry_java.so") != null);
            assertTrue(archive.getEntry("lib/x86_64/libfoundry_android.so") != null);
            assertFalse(archive.stream().anyMatch(entry -> entry.getName().contains("arm64-v8a")));
        }
        String mapping =
                Files.readString(project.resolve("build/outputs/mapping/release/mapping.txt"));
        assertTrue(mapping.contains("games.cafecito.foundry.generated.FoundryGeneratedBootstrap"));
        assertTrue(mapping.contains("example.DemoRegistry"));
        assertTrue(mapping.contains("example.DemoRegistry$1"));
        assertTrue(
                Files.readString(project.resolve("build/outputs/apk/release/output-metadata.json"))
                        .contains("games.cafecito.test.custom"));
        String mergedManifest = mergedManifest(project, "release");
        assertTrue(
                mergedManifest.contains(
                        "android:name=\"games.cafecito.foundry.generated."
                                + "FoundryGeneratedStartupProvider\""));
        assertTrue(
                mergedManifest.contains(
                        "android:authorities=\"games.cafecito.test.custom."
                                + "foundry-java-startup\""));
        assertTrue(mergedManifest.contains("android:exported=\"false\""));
        assertTrue(mergedManifest.contains("android:initOrder=\"100\""));
        assertFalse(mergedManifest.contains("android:process="));
    }

    @Test
    void debugBuildUsesTheNamespaceAsTheDefaultApplicationId() throws IOException {
        Path binding =
                bindingAar(
                        temporaryDirectory.resolve("debug-binding.aar"),
                        "demo",
                        "example.DemoRegistry",
                        List.of("x86_64"));
        Path project = androidProject("debug-default-id", binding, List.of("x86_64"));
        Files.writeString(
                project.resolve("build.gradle"),
                Files.readString(project.resolve("build.gradle"))
                        .replace("        applicationId 'games.cafecito.test.custom'\n", ""));
        writeBootstrapStubs(project);

        run(project, "assembleDebug");

        assertArrayEquals(
                BINDING_CONFIGURATION,
                Files.readAllBytes(
                        project.resolve(
                                "build/generated/assets/generateDebugFoundryJavaRegistry/"
                                        + "FoundryJava.foundryextension")));
        assertTrue(
                Files.readString(project.resolve("build/outputs/apk/debug/output-metadata.json"))
                        .contains("games.cafecito.test"));
        assertTrue(
                mergedManifest(project, "debug")
                        .contains(
                                "android:authorities=\"games.cafecito.test."
                                        + "foundry-java-startup\""));
    }

    @Test
    void zeroModuleVariantIgnoresReservedPlaceholderValues() throws IOException {
        Path binding =
                bindingAarWithoutDescriptor(
                        temporaryDirectory.resolve("zero-module-placeholder-binding.aar"),
                        List.of("x86_64"));
        Path project =
                androidProject(
                        "zero-module-reserved-placeholders", binding, List.of("x86_64"));
        Files.writeString(
                project.resolve("build.gradle"),
                Files.readString(project.resolve("build.gradle"))
                        .replace(
                                "        applicationId 'games.cafecito.test.custom'\n",
                                """
                                        applicationId 'games.cafecito.test.custom'
                                        manifestPlaceholders = [
                                            foundryJavaStartupProvider: 'example.UnrelatedProvider',
                                            foundryJavaStartupAuthority: 'shared.authority'
                                        ]
                                """));

        BuildResult result = run(project, "assembleDebug");

        assertEquals(TaskOutcome.SUCCESS, result.task(":assembleDebug").getOutcome());
        assertFalse(
                mergedManifest(project, "debug")
                        .contains("FoundryGeneratedStartupProvider"));
    }

    @Test
    void variantPlaceholderCallbacksCannotRedirectModuleBearingStartup() throws IOException {
        Path binding =
                bindingAar(
                        temporaryDirectory.resolve("placeholder-order-binding.aar"),
                        "demo",
                        "example.DemoRegistry",
                        List.of("x86_64"));
        Path project = androidProject("placeholder-order", binding, List.of("x86_64"));
        writeBootstrapStubs(project);
        Files.writeString(
                project.resolve("build.gradle"),
                Files.readString(project.resolve("build.gradle"))
                        .replace(
                                "    id 'games.cafecito.foundry.java'\n",
                                "")
                        .replace(
                                "android {\n",
                                """
                                androidComponents.onVariants(androidComponents.selector().all()) { variant ->
                                    variant.manifestPlaceholders.put(
                                        'foundryJavaStartupAuthority',
                                        'before.foundry-java-startup')
                                }
                                apply plugin: 'games.cafecito.foundry.java'
                                androidComponents.onVariants(androidComponents.selector().all()) { variant ->
                                    variant.manifestPlaceholders.put(
                                        'foundryJavaStartupProvider',
                                        'example.AfterProvider')
                                    variant.manifestPlaceholders.put(
                                        'foundryJavaStartupAuthority',
                                        'after.foundry-java-startup')
                                }
                                android {
                                """));

        BuildResult result = run(project, "assembleDebug");

        assertEquals(TaskOutcome.SUCCESS, result.task(":assembleDebug").getOutcome());
        String mergedManifest = mergedManifest(project, "debug");
        assertTrue(
                mergedManifest.contains(
                        "android:name=\"games.cafecito.foundry.generated."
                                + "FoundryGeneratedStartupProvider\""));
        assertTrue(
                mergedManifest.contains(
                        "android:authorities=\"games.cafecito.test.custom."
                                + "foundry-java-startup\""));
        assertFalse(mergedManifest.contains("example.AfterProvider"));
        assertFalse(mergedManifest.contains("after.foundry-java-startup"));
    }

    @Test
    void mergedManifestAuthorityCollisionFailsWithVariantProviderAndAuthority()
            throws IOException {
        Path binding =
                bindingAar(
                        temporaryDirectory.resolve("authority-collision-binding.aar"),
                        "demo",
                        "example.DemoRegistry",
                        List.of("x86_64"));
        Path project = androidProject("authority-collision", binding, List.of("x86_64"));
        Files.writeString(
                project.resolve("src/main/AndroidManifest.xml"),
                """
                <manifest xmlns:android="http://schemas.android.com/apk/res/android">
                    <application>
                        <provider
                            android:name="example.ConflictingProvider"
                            android:authorities="${applicationId}.foundry-java-startup"
                            android:exported="false" />
                    </application>
                </manifest>
                """);

        BuildResult failure = runAndFail(project, "assembleDebug");

        assertTrue(failure.getOutput().contains("Foundry-Java variant debug"));
        assertTrue(failure.getOutput().contains("example.ConflictingProvider"));
        assertTrue(
                failure.getOutput()
                        .contains("games.cafecito.test.custom.foundry-java-startup"));
    }

    @Test
    void mergedManifestStartupOverrideFailsWithEveryCriticalAttribute() throws IOException {
        Path binding =
                bindingAar(
                        temporaryDirectory.resolve("startup-override-binding.aar"),
                        "demo",
                        "example.DemoRegistry",
                        List.of("x86_64"));
        Path project = androidProject("startup-override", binding, List.of("x86_64"));
        writeBootstrapStubs(project);
        Files.writeString(
                project.resolve("build.gradle"),
                Files.readString(project.resolve("build.gradle"))
                        .replace(
                                "    id 'games.cafecito.foundry.java'\n",
                                "")
                        .replace(
                                "android {\n",
                                """
                                abstract class CorruptStartupManifest extends DefaultTask {
                                    @org.gradle.api.tasks.InputFile
                                    @org.gradle.api.tasks.PathSensitive(
                                        org.gradle.api.tasks.PathSensitivity.NONE)
                                    abstract org.gradle.api.file.RegularFileProperty getInputManifest()

                                    @org.gradle.api.tasks.OutputFile
                                    abstract org.gradle.api.file.RegularFileProperty getOutputManifest()

                                    @org.gradle.api.tasks.TaskAction
                                    void corrupt() {
                                        def source = inputManifest.get().asFile.text
                                        def changed = source
                                            .replace(
                                                'android:authorities="games.cafecito.test.custom.foundry-java-startup"',
                                                'android:authorities="games.cafecito.test.custom.foundry-java-startup;extra.authority"')
                                            .replace(
                                                'android:exported="false"',
                                                'android:exported="true"')
                                            .replace(
                                                'android:initOrder="100"',
                                                'android:enabled="false" android:initOrder="99" android:process=":wrong"')
                                        if (changed == source) {
                                            throw new GradleException(
                                                'Expected generated startup provider in merged manifest')
                                        }
                                        def output = outputManifest.get().asFile
                                        output.parentFile.mkdirs()
                                        output.text = changed
                                    }
                                }
                                androidComponents.onVariants(androidComponents.selector().all()) { variant ->
                                    def task = tasks.register(
                                        "corrupt${variant.name.capitalize()}StartupManifest",
                                        CorruptStartupManifest)
                                    variant.artifacts
                                        .use(task)
                                        .wiredWithFiles(
                                            { it.inputManifest },
                                            { it.outputManifest })
                                        .toTransform(
                                            com.android.build.api.artifact.SingleArtifact.MERGED_MANIFEST.INSTANCE)
                                }
                                apply plugin: 'games.cafecito.foundry.java'
                                android {
                                """));

        BuildResult failure = runAndFail(project, "assembleDebug");

        assertTrue(failure.getOutput().contains("Foundry-Java variant debug"));
        assertTrue(
                failure.getOutput()
                        .contains(
                                "games.cafecito.foundry.generated."
                                        + "FoundryGeneratedStartupProvider"));
        assertTrue(failure.getOutput().contains("authority expected=games.cafecito.test.custom"));
        assertTrue(failure.getOutput().contains("actual=games.cafecito.test.custom"));
        assertTrue(failure.getOutput().contains("extra.authority"));
        assertTrue(failure.getOutput().contains("exported expected=false, actual=true"));
        assertTrue(failure.getOutput().contains("process expected=<empty>, actual=:wrong"));
        assertTrue(failure.getOutput().contains("initOrder expected=100, actual=99"));
        assertTrue(failure.getOutput().contains("enabled expected=not false, actual=false"));
    }

    @Test
    void agp891DownstreamUsesPublicVariantsAndPackagesTheValidatedPayload() throws Exception {
        Path host =
                aar(
                        temporaryDirectory.resolve("agp-8.9.1-host.aar"),
                        null,
                        null,
                        List.of(
                                new RawZipEntry(
                                        "jni/x86_64/libfoundry_android.so", new byte[] {1})));
        Path binding =
                bindingAar(
                        temporaryDirectory.resolve("agp-8.9.1-binding.aar"),
                        "demo",
                        "example.DemoRegistry",
                        List.of("arm64-v8a", "x86_64"));
        Path project =
                androidProject("agp-8.9.1-downstream", List.of(host, binding), List.of("x86_64"));
        writeIsolatedGradleJvm(project, "agp891");
        Files.writeString(
                project.resolve("build.gradle"),
                Files.readString(project.resolve("build.gradle"))
                        + "\nprintln 'AGP_VERSION='"
                        + " + com.android.Version.ANDROID_GRADLE_PLUGIN_VERSION\n");
        writeBootstrapStubs(project);

        BuildResult first =
                runWithFoundryPluginOnly(project, "assembleDebug", "--configuration-cache");
        BuildResult second =
                runWithFoundryPluginOnly(project, "assembleDebug", "--configuration-cache");

        assertEquals(
                TaskOutcome.SUCCESS, first.task(":generateDebugFoundryJavaRegistry").getOutcome());
        assertTrue(first.getOutput().contains("AGP_VERSION=8.9.1"));
        assertTrue(second.getOutput().contains("Reusing configuration cache."));
        Path generatedAssets =
                project.resolve("build/generated/assets/generateDebugFoundryJavaRegistry");
        assertTrue(
                Files.readString(generatedAssets.resolve("foundry_java/registry-index-v2.txt"))
                        .contains("module=demo|example.DemoRegistry"));
        assertArrayEquals(
                BINDING_CONFIGURATION,
                Files.readAllBytes(generatedAssets.resolve("FoundryJava.foundryextension")));
        assertTrue(
                Files.readString(
                                project.resolve(
                                        "build/generated/java/"
                                                + "generateDebugFoundryJavaRegistry/"
                                                + "games/cafecito/foundry/generated/"
                                                + "FoundryGeneratedBootstrap.java"))
                        .contains("example.DemoRegistry.PROVIDER"));
        Path apk =
                Files.list(project.resolve("build/outputs/apk/debug"))
                        .filter(path -> path.getFileName().toString().endsWith(".apk"))
                        .findFirst()
                        .orElseThrow();
        try (java.util.zip.ZipFile archive = new java.util.zip.ZipFile(apk.toFile())) {
            assertTrue(archive.getEntry("lib/x86_64/libfoundry_java.so") != null);
            assertTrue(archive.getEntry("lib/x86_64/libfoundry_android.so") != null);
            assertFalse(archive.stream().anyMatch(entry -> entry.getName().contains("arm64-v8a")));
            assertEquals(
                    List.of("assets/FoundryJava.foundryextension"),
                    archive.stream()
                            .map(ZipEntry::getName)
                            .filter(name -> name.endsWith("FoundryJava.foundryextension"))
                            .toList());
            assertArrayEquals(
                    BINDING_CONFIGURATION,
                    archive.getInputStream(archive.getEntry("assets/FoundryJava.foundryextension"))
                            .readAllBytes());
        }
    }

    @Test
    void stagedMavenTopologyPreservesTheHostAndReusesConfigurationCache() throws Exception {
        Path repository = temporaryDirectory.resolve("staged-maven-repository");
        Path plugin = pluginJar(temporaryDirectory.resolve("foundry-java-gradle-plugin-1.jar"));
        Path annotations = emptyJar(temporaryDirectory.resolve("foundry-java-annotations-1.jar"));
        Path apiModel = emptyJar(temporaryDirectory.resolve("foundry-java-api-model-1.jar"));
        Path runtime = emptyJar(temporaryDirectory.resolve("foundry-java-runtime-1.jar"));
        Path binding =
                bindingAar(
                        temporaryDirectory.resolve("foundry-java-android-1.aar"),
                        "demo",
                        "example.DemoRegistry",
                        List.of("arm64-v8a", "x86_64"));
        Path host =
                aar(
                        temporaryDirectory.resolve("foundry-host-1.aar"),
                        null,
                        null,
                        List.of(
                                new RawZipEntry(
                                        "jni/x86_64/libfoundry_android.so", new byte[] {1})));
        publishMavenArtifact(
                repository,
                "games.cafecito",
                "foundry-java-gradle-plugin",
                "1",
                "jar",
                plugin,
                List.of());
        publishMavenArtifact(
                repository,
                "games.cafecito.foundry.java",
                "games.cafecito.foundry.java.gradle.plugin",
                "1",
                "pom",
                null,
                List.of(
                        new MavenDependency(
                                "games.cafecito", "foundry-java-gradle-plugin", "1", "compile")));
        publishMavenArtifact(
                repository,
                "games.cafecito",
                "foundry-java-annotations",
                "1",
                "jar",
                annotations,
                List.of());
        publishMavenArtifact(
                repository,
                "games.cafecito",
                "foundry-java-api-model",
                "1",
                "jar",
                apiModel,
                List.of(
                        new MavenDependency(
                                "games.cafecito", "foundry-java-annotations", "1", "compile")));
        publishMavenArtifact(
                repository,
                "games.cafecito",
                "foundry-java-runtime",
                "1",
                "jar",
                runtime,
                List.of(
                        new MavenDependency(
                                "games.cafecito", "foundry-java-api-model", "1", "compile"),
                        new MavenDependency(
                                "games.cafecito", "foundry-java-annotations", "1", "runtime")));
        publishMavenArtifact(
                repository,
                "games.cafecito",
                "foundry-java-android",
                "1",
                "aar",
                binding,
                List.of(
                        new MavenDependency(
                                "games.cafecito", "foundry-java-runtime", "1", "compile")));
        publishMavenArtifact(
                repository, "games.cafecito.host", "foundry-host", "1", "aar", host, List.of());
        Path project = androidProject("staged-maven-topology");
        writeIsolatedGradleJvm(project, "staged-maven");
        Files.writeString(
                project.resolve("settings.gradle"),
                """
                pluginManagement {
                    repositories {
                        maven { url = uri('%s') }
                        google()
                        mavenCentral()
                        gradlePluginPortal()
                    }
                }
                dependencyResolutionManagement {
                    repositories {
                        maven { url = uri('%s') }
                        google()
                        mavenCentral()
                    }
                }
                rootProject.name = 'staged-maven-topology'
                """
                        .formatted(repository.toUri(), repository.toUri()));
        Files.writeString(
                project.resolve("build.gradle"),
                Files.readString(project.resolve("build.gradle"))
                                .replace(
                                        "id 'com.android.application'",
                                        "id 'com.android.application' version '8.10.0'")
                                .replace(
                                        "id 'games.cafecito.foundry.java'",
                                        "id 'games.cafecito.foundry.java' version '1'")
                        + """

                        dependencies {
                            implementation 'games.cafecito:foundry-java-android:1'
                            implementation 'games.cafecito.host:foundry-host:1'
                        }
                        foundryJava { requestedAbis.set(['x86_64']) }
                        """);
        writeBootstrapStubs(project);

        BuildResult first =
                runWithoutPluginClasspath(project, "assembleRelease", "--configuration-cache");
        BuildResult second =
                runWithoutPluginClasspath(project, "assembleRelease", "--configuration-cache");

        assertEquals(
                TaskOutcome.SUCCESS,
                first.task(":generateReleaseFoundryJavaRegistry").getOutcome());
        assertTrue(second.getOutput().contains("Reusing configuration cache."));
        Path generatedAssets =
                project.resolve("build/generated/assets/generateReleaseFoundryJavaRegistry");
        assertTrue(
                Files.readString(generatedAssets.resolve("foundry_java/registry-index-v2.txt"))
                        .contains("module=demo|example.DemoRegistry"));
        assertArrayEquals(
                BINDING_CONFIGURATION,
                Files.readAllBytes(generatedAssets.resolve("FoundryJava.foundryextension")));
        assertTrue(
                Files.readString(
                                project.resolve(
                                        "build/generated/java/"
                                                + "generateReleaseFoundryJavaRegistry/"
                                                + "games/cafecito/foundry/generated/"
                                                + "FoundryGeneratedBootstrap.java"))
                        .contains("example.DemoRegistry.PROVIDER"));
        Path apk =
                Files.list(project.resolve("build/outputs/apk/release"))
                        .filter(path -> path.getFileName().toString().endsWith(".apk"))
                        .findFirst()
                        .orElseThrow();
        try (java.util.zip.ZipFile archive = new java.util.zip.ZipFile(apk.toFile())) {
            assertTrue(archive.getEntry("lib/x86_64/libfoundry_java.so") != null);
            assertTrue(archive.getEntry("lib/x86_64/libfoundry_android.so") != null);
            assertFalse(archive.stream().anyMatch(entry -> entry.getName().contains("arm64-v8a")));
        }
    }

    @Test
    void androidLibraryApplicationIsRejectedWithAConcretePluginDiagnostic() throws IOException {
        Path project = androidProject("library-misuse");
        Files.writeString(
                project.resolve("build.gradle"),
                Files.readString(project.resolve("build.gradle"))
                        .replace("com.android.application", "com.android.library"));

        BuildResult failure = runAndFail(project, "tasks");

        assertTrue(failure.getOutput().contains("requires com.android.application"));
        assertTrue(failure.getOutput().contains("com.android.library"));
    }

    private Path project(String name, List<Path> modules) throws IOException {
        Path project = temporaryDirectory.resolve(name);
        Files.createDirectories(project);
        Files.writeString(
                project.resolve("settings.gradle"), "rootProject.name = '" + name + "'\n");
        writeBuild(project, modules);
        return project;
    }

    private void writeBuild(Path project, List<Path> modules) throws IOException {
        String dependencies =
                modules.stream()
                        .map(
                                path ->
                                        "    foundryJavaModules files('"
                                                + path.toAbsolutePath()
                                                + "')")
                        .reduce((left, right) -> left + "\n" + right)
                        .orElse("");
        Files.writeString(
                project.resolve("build.gradle"),
                """
                plugins {
                    id 'games.cafecito.foundry.java'
                }
                dependencies {
                %s
                }
                """
                        .formatted(dependencies));
    }

    private Path projectWithPayloads(String name, List<Path> payloads, List<String> abis)
            throws IOException {
        Path project = project(name, payloads);
        String requestedAbis =
                abis.stream()
                        .map(abi -> "'" + abi + "'")
                        .reduce((left, right) -> left + ", " + right)
                        .orElse("");
        Files.writeString(
                project.resolve("build.gradle"),
                Files.readString(project.resolve("build.gradle"))
                        + "\nfoundryJava { requestedAbis.set(["
                        + requestedAbis
                        + "]) }\n");
        return project;
    }

    private Path androidProject(String name) throws IOException {
        Path project = temporaryDirectory.resolve(name);
        Files.createDirectories(project.resolve("src/main"));
        Files.writeString(
                project.resolve("settings.gradle"),
                """
                pluginManagement {
                    repositories {
                        google()
                        mavenCentral()
                        gradlePluginPortal()
                    }
                }
                dependencyResolutionManagement {
                    repositories {
                        google()
                        mavenCentral()
                    }
                }
                rootProject.name = '%s'
                """
                        .formatted(name));
        Files.writeString(
                project.resolve("build.gradle"),
                """
                plugins {
                    id 'com.android.application'
                    id 'games.cafecito.foundry.java'
                }
                android {
                    namespace 'games.cafecito.test'
                    compileSdk 36
                    compileOptions {
                        sourceCompatibility JavaVersion.VERSION_17
                        targetCompatibility JavaVersion.VERSION_17
                    }
                    defaultConfig {
                        applicationId 'games.cafecito.test.custom'
                        minSdk 23
                        targetSdk 36
                        versionCode 1
                        versionName '1'
                    }
                    buildTypes {
                        release {
                            minifyEnabled true
                            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
                        }
                    }
                }
                """);
        Files.writeString(project.resolve("src/main/AndroidManifest.xml"), "<manifest />\n");
        Path search = Path.of("").toAbsolutePath();
        while (search != null) {
            Path localProperties = search.resolve("local.properties");
            if (Files.isRegularFile(localProperties)) {
                Files.copy(localProperties, project.resolve("local.properties"));
                break;
            }
            search = search.getParent();
        }
        return project;
    }

    private void writeBootstrapStubs(Path project) throws IOException {
        Path runtime = project.resolve("src/main/java/games/cafecito/foundry/runtime");
        Path android = project.resolve("src/main/java/games/cafecito/foundry/java");
        Path example = project.resolve("src/main/java/example");
        Files.createDirectories(runtime);
        Files.createDirectories(android);
        Files.createDirectories(example);
        Files.writeString(
                android.resolve("FoundryJavaStartupProvider.java"),
                """
                package games.cafecito.foundry.java;

                public abstract class FoundryJavaStartupProvider
                        extends android.content.ContentProvider {
                    protected abstract Object bootstrap();

                    @Override
                    public boolean onCreate() {
                        return bootstrap() != null;
                    }

                    @Override
                    public android.database.Cursor query(
                            android.net.Uri uri,
                            String[] projection,
                            String selection,
                            String[] selectionArgs,
                            String sortOrder) {
                        return null;
                    }

                    @Override
                    public String getType(android.net.Uri uri) {
                        return null;
                    }

                    @Override
                    public android.net.Uri insert(
                            android.net.Uri uri, android.content.ContentValues values) {
                        return null;
                    }

                    @Override
                    public int delete(
                            android.net.Uri uri, String selection, String[] selectionArgs) {
                        return 0;
                    }

                    @Override
                    public int update(
                            android.net.Uri uri,
                            android.content.ContentValues values,
                            String selection,
                            String[] selectionArgs) {
                        return 0;
                    }
                }
                """);
        Files.writeString(
                runtime.resolve("FoundryModuleProvider.java"),
                """
                package games.cafecito.foundry.runtime;

                public interface FoundryModuleProvider {
                    FoundryModuleDescriptor descriptor();
                }
                """);
        Files.writeString(
                runtime.resolve("FoundryRegistryBootstrap.java"),
                """
                package games.cafecito.foundry.runtime;

                public final class FoundryRegistryBootstrap {
                    public FoundryRegistryBootstrap(
                            java.util.List<? extends FoundryModuleProvider> providers) {}
                }
                """);
        Files.writeString(
                runtime.resolve("FoundryExtensionAccess.java"),
                """
                package games.cafecito.foundry.runtime;

                public interface FoundryExtensionAccess {
                    Object construct(Object context, Object lease);
                    Object invoke(Object target, String name, Object[] arguments);
                    Object getProperty(Object target, String name);
                    void setProperty(Object target, String name, Object value);
                }
                """);
        Files.writeString(
                runtime.resolve("FoundryClassDescriptor.java"),
                """
                package games.cafecito.foundry.runtime;

                public record FoundryClassDescriptor(FoundryExtensionAccess access) {}
                """);
        Files.writeString(
                runtime.resolve("FoundryModuleDescriptor.java"),
                """
                package games.cafecito.foundry.runtime;

                public record FoundryModuleDescriptor(
                        java.util.List<FoundryClassDescriptor> classes) {}
                """);
        Files.writeString(
                example.resolve("Extension_FoundryTrampoline.java"),
                """
                package example;

                public final class Extension_FoundryTrampoline {
                    public static Object construct(Object context, Object lease) {
                        return new Object();
                    }
                    public static Object invoke(Object target, String name, Object[] arguments) {
                        return null;
                    }
                    public static Object getProperty(Object target, String name) {
                        return null;
                    }
                    public static void setProperty(Object target, String name, Object value) {}
                }
                """);
        Files.writeString(
                example.resolve("DemoRegistry.java"),
                """
                package example;

                public final class DemoRegistry
                        implements games.cafecito.foundry.runtime.FoundryModuleProvider {
                    public static final games.cafecito.foundry.runtime.FoundryModuleProvider
                            PROVIDER = new DemoRegistry();

                    private static final games.cafecito.foundry.runtime.FoundryModuleDescriptor
                            DESCRIPTOR =
                                    new games.cafecito.foundry.runtime.FoundryModuleDescriptor(
                                            java.util.List.of(
                                                    new games.cafecito.foundry.runtime
                                                            .FoundryClassDescriptor(
                                                            new games.cafecito.foundry.runtime
                                                                    .FoundryExtensionAccess() {
                                                                @Override
                                                                public Object construct(
                                                                        Object context,
                                                                        Object lease) {
                                                                    return Extension_FoundryTrampoline
                                                                            .construct(context, lease);
                                                                }

                                                                @Override
                                                                public Object invoke(
                                                                        Object target,
                                                                        String name,
                                                                        Object[] arguments) {
                                                                    return Extension_FoundryTrampoline
                                                                            .invoke(
                                                                                    target,
                                                                                    name,
                                                                                    arguments);
                                                                }

                                                                @Override
                                                                public Object getProperty(
                                                                        Object target,
                                                                        String name) {
                                                                    return Extension_FoundryTrampoline
                                                                            .getProperty(target, name);
                                                                }

                                                                @Override
                                                                public void setProperty(
                                                                        Object target,
                                                                        String name,
                                                                        Object value) {
                                                                    Extension_FoundryTrampoline
                                                                            .setProperty(
                                                                                    target,
                                                                                    name,
                                                                                    value);
                                                                }
                                                            })));

                    private DemoRegistry() {}

                    @Override
                    public games.cafecito.foundry.runtime.FoundryModuleDescriptor descriptor() {
                        return DESCRIPTOR;
                    }
                }
                """);
    }

    private Path androidProject(String name, Path binding, List<String> requestedAbis)
            throws IOException {
        return androidProject(name, List.of(binding), requestedAbis);
    }

    private Path androidProject(String name, List<Path> artifacts, List<String> requestedAbis)
            throws IOException {
        Path project = androidProject(name);
        String abis =
                requestedAbis.stream()
                        .map(abi -> "'" + abi + "'")
                        .reduce((left, right) -> left + ", " + right)
                        .orElse("");
        String dependencies =
                artifacts.stream()
                        .map(
                                artifact ->
                                        "    implementation files('"
                                                + artifact.toAbsolutePath()
                                                + "')")
                        .reduce((left, right) -> left + "\n" + right)
                        .orElse("");
        Files.writeString(
                project.resolve("build.gradle"),
                Files.readString(project.resolve("build.gradle"))
                        + "\ndependencies {\n"
                        + dependencies
                        + "\n}\n"
                        + "foundryJava { requestedAbis.set(["
                        + abis
                        + "]) }\n");
        return project;
    }

    private BuildResult run(Path project, String... arguments) {
        return GradleRunner.create()
                .withProjectDir(project.toFile())
                .withPluginClasspath()
                .withArguments(arguments)
                .forwardOutput()
                .build();
    }

    private BuildResult runAndFail(Path project, String... arguments) {
        return GradleRunner.create()
                .withProjectDir(project.toFile())
                .withPluginClasspath()
                .withArguments(arguments)
                .forwardOutput()
                .buildAndFail();
    }

    private String mergedManifest(Path project, String variant) throws IOException {
        Path root = project.resolve("build/intermediates/merged_manifest").resolve(variant);
        try (var paths = Files.walk(root)) {
            Path manifest =
                    paths.filter(path -> path.getFileName().toString().equals("AndroidManifest.xml"))
                            .findFirst()
                            .orElseThrow();
            return Files.readString(manifest);
        }
    }

    private BuildResult runWithFoundryPluginOnly(Path project, String... arguments)
            throws Exception {
        Path classes =
                Path.of(
                        FoundryJavaPlugin.class
                                .getProtectionDomain()
                                .getCodeSource()
                                .getLocation()
                                .toURI());
        Path descriptor =
                Path.of(
                        FoundryJavaPlugin.class
                                .getClassLoader()
                                .getResource(
                                        "META-INF/gradle-plugins/"
                                                + "games.cafecito.foundry.java.properties")
                                .toURI());
        Path resources = descriptor.getParent().getParent().getParent();
        List<File> pluginClasspath = new ArrayList<>(List.of(classes.toFile(), resources.toFile()));
        for (String entry :
                System.getProperty("foundry.agp891.plugin.classpath")
                        .split(java.util.regex.Pattern.quote(File.pathSeparator))) {
            pluginClasspath.add(Path.of(entry).toFile());
        }
        return GradleRunner.create()
                .withProjectDir(project.toFile())
                .withPluginClasspath(pluginClasspath)
                .withArguments(arguments)
                .forwardOutput()
                .build();
    }

    private BuildResult runWithoutPluginClasspath(Path project, String... arguments) {
        return GradleRunner.create()
                .withProjectDir(project.toFile())
                .withArguments(arguments)
                .forwardOutput()
                .build();
    }

    private static void writeIsolatedGradleJvm(Path project, String identity) throws IOException {
        Files.writeString(
                project.resolve("gradle.properties"),
                "org.gradle.jvmargs=-Xmx768m -XX:MaxMetaspaceSize=768m"
                        + " -Dfoundry.testkit.identity="
                        + identity
                        + "\n");
    }

    private Path moduleJar(Path output, String module, String registry) throws IOException {
        return moduleJarAtPath(
                output,
                "META-INF/foundry-java/modules/" + module + ".descriptor",
                descriptor(module, registry));
    }

    private Path moduleJarAtPath(Path output, String descriptorPath, String descriptorContents)
            throws IOException {
        Files.createDirectories(output.getParent());
        try (JarOutputStream archive = new JarOutputStream(Files.newOutputStream(output))) {
            JarEntry entry = new JarEntry(descriptorPath);
            entry.setTime(0);
            archive.putNextEntry(entry);
            archive.write(descriptorContents.getBytes(StandardCharsets.UTF_8));
            archive.closeEntry();
        }
        return output;
    }

    private Path bindingAar(Path output, String module, String registry, List<String> abis)
            throws IOException {
        return bindingAar(output, descriptor(module, registry), abis);
    }

    private Path bindingAarWithoutDescriptor(Path output, List<String> abis) throws IOException {
        return bindingAar(output, null, abis);
    }

    private Path bindingAar(Path output, String descriptorContents, List<String> abis)
            throws IOException {
        Files.createDirectories(output.getParent());
        String descriptorPath = null;
        if (descriptorContents != null) {
            String module =
                    descriptorContents
                            .lines()
                            .filter(line -> line.startsWith("module="))
                            .findFirst()
                            .orElseThrow()
                            .substring("module=".length());
            descriptorPath = "META-INF/foundry-java/modules/" + module + ".descriptor";
        }
        return bindingAarAtPath(output, descriptorPath, descriptorContents, abis);
    }

    private Path bindingAarAtPath(
            Path output, String descriptorPath, String descriptorContents, List<String> abis)
            throws IOException {
        Files.createDirectories(output.getParent());
        String registry =
                descriptorContents == null
                        ? "example.DemoRegistry"
                        : descriptorContents
                                .lines()
                                .filter(line -> line.startsWith("registry="))
                                .findFirst()
                                .orElseThrow()
                                .substring("registry=".length());
        byte[] classesBytes = classesJar(descriptorPath, descriptorContents, true);
        try (ZipOutputStream archive = new ZipOutputStream(Files.newOutputStream(output))) {
            ZipEntry manifest = new ZipEntry("AndroidManifest.xml");
            manifest.setTime(0);
            archive.putNextEntry(manifest);
            archive.write(
                    ("<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\" "
                                    + "package=\"games.cafecito.binding\" />\n")
                            .getBytes(StandardCharsets.UTF_8));
            archive.closeEntry();
            ZipEntry classes = new ZipEntry("classes.jar");
            classes.setTime(0);
            archive.putNextEntry(classes);
            archive.write(classesBytes);
            archive.closeEntry();
            ZipEntry consumerRules = new ZipEntry("proguard.txt");
            consumerRules.setTime(0);
            archive.putNextEntry(consumerRules);
            archive.write(
                    ("""
                    -keep class games.cafecito.foundry.generated.FoundryGeneratedBootstrap { *; }
                    -keep class %s {
                        public static final games.cafecito.foundry.runtime.FoundryModuleProvider PROVIDER;
                        public games.cafecito.foundry.runtime.FoundryModuleDescriptor descriptor();
                    }
                    -keep class example.Extension_FoundryTrampoline { public static *** *(...); }
                    """
                                    .formatted(registry))
                            .getBytes(StandardCharsets.UTF_8));
            archive.closeEntry();
            for (String abi : abis) {
                ZipEntry bridge = new ZipEntry("jni/" + abi + "/libfoundry_java.so");
                bridge.setTime(0);
                archive.putNextEntry(bridge);
                archive.write(new byte[] {0});
                archive.closeEntry();
            }
        }
        return output;
    }

    private Path bindingAarWithDuplicatePayload(Path output, String duplicatePath)
            throws IOException {
        Files.createDirectories(output.getParent());
        boolean duplicateConfiguration = duplicatePath.equals("FoundryJava.foundryextension");
        byte[] classesBytes =
                classesJar(
                        "META-INF/foundry-java/modules/demo.descriptor",
                        descriptor("demo", "example.DemoRegistry"),
                        !duplicateConfiguration);
        List<RawZipEntry> entries =
                new ArrayList<>(
                        List.of(
                                new RawZipEntry(
                                        "AndroidManifest.xml",
                                        "<manifest package=\"games.cafecito.binding\" />\n"
                                                .getBytes(StandardCharsets.UTF_8)),
                                new RawZipEntry("classes.jar", classesBytes)));
        if (duplicateConfiguration) {
            entries.add(new RawZipEntry(duplicatePath, BINDING_CONFIGURATION));
            entries.add(new RawZipEntry(duplicatePath, BINDING_CONFIGURATION));
            entries.add(new RawZipEntry("jni/x86_64/libfoundry_java.so", new byte[] {0}));
        } else {
            entries.add(new RawZipEntry(duplicatePath, new byte[] {0}));
            entries.add(new RawZipEntry(duplicatePath, new byte[] {0}));
        }
        writeRawZip(output, entries);
        return output;
    }

    private Path aar(
            Path output,
            String descriptorPath,
            String descriptorContents,
            List<RawZipEntry> payloads)
            throws IOException {
        List<RawZipEntry> entries =
                new ArrayList<>(
                        List.of(
                                new RawZipEntry(
                                        "AndroidManifest.xml",
                                        "<manifest package=\"games.cafecito.fixture\" />\n"
                                                .getBytes(StandardCharsets.UTF_8)),
                                new RawZipEntry(
                                        "classes.jar",
                                        classesJar(descriptorPath, descriptorContents, false))));
        entries.addAll(payloads);
        writeRawZip(output, entries);
        return output;
    }

    private Path pluginJar(Path output) throws Exception {
        Path classes =
                Path.of(
                        FoundryJavaPlugin.class
                                .getProtectionDomain()
                                .getCodeSource()
                                .getLocation()
                                .toURI());
        Path descriptor =
                Path.of(
                        FoundryJavaPlugin.class
                                .getClassLoader()
                                .getResource(
                                        "META-INF/gradle-plugins/"
                                                + "games.cafecito.foundry.java.properties")
                                .toURI());
        Path resources = descriptor.getParent().getParent().getParent();
        Set<String> added = new HashSet<>();
        try (JarOutputStream archive = new JarOutputStream(Files.newOutputStream(output))) {
            addJarTree(archive, classes, added);
            addJarTree(archive, resources, added);
        }
        return output;
    }

    private static void addJarTree(JarOutputStream archive, Path root, Set<String> added)
            throws IOException {
        try (var paths = Files.walk(root)) {
            for (Path path : paths.filter(Files::isRegularFile).sorted().toList()) {
                String name = root.relativize(path).toString().replace('\\', '/');
                if (!added.add(name)) {
                    continue;
                }
                JarEntry entry = new JarEntry(name);
                entry.setTime(0);
                archive.putNextEntry(entry);
                archive.write(Files.readAllBytes(path));
                archive.closeEntry();
            }
        }
    }

    private static Path emptyJar(Path output) throws IOException {
        try (JarOutputStream ignored = new JarOutputStream(Files.newOutputStream(output))) {
            return output;
        }
    }

    private static void publishMavenArtifact(
            Path repository,
            String group,
            String artifact,
            String version,
            String packaging,
            Path binary,
            List<MavenDependency> dependencies)
            throws IOException {
        Path directory =
                repository.resolve(group.replace('.', '/')).resolve(artifact).resolve(version);
        Files.createDirectories(directory);
        if (binary != null) {
            Files.copy(binary, directory.resolve(artifact + "-" + version + "." + packaging));
        }
        String dependencyXml =
                dependencies.stream()
                        .map(
                                dependency ->
                                        """
                                        <dependency>
                                          <groupId>%s</groupId>
                                          <artifactId>%s</artifactId>
                                          <version>%s</version>
                                          <scope>%s</scope>
                                        </dependency>
                                        """
                                                .formatted(
                                                        dependency.group(),
                                                        dependency.artifact(),
                                                        dependency.version(),
                                                        dependency.scope()))
                        .reduce((left, right) -> left + right)
                        .orElse("");
        Files.writeString(
                directory.resolve(artifact + "-" + version + ".pom"),
                """
                <project xmlns="http://maven.apache.org/POM/4.0.0">
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>%s</groupId>
                  <artifactId>%s</artifactId>
                  <version>%s</version>
                  <packaging>%s</packaging>
                  <dependencies>
                %s
                  </dependencies>
                </project>
                """
                        .formatted(group, artifact, version, packaging, dependencyXml));
    }

    private static byte[] classesJar(
            String descriptorPath, String descriptorContents, boolean includeConfiguration)
            throws IOException {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        try (JarOutputStream classes = new JarOutputStream(output)) {
            if (descriptorContents != null) {
                JarEntry descriptor = new JarEntry(descriptorPath);
                descriptor.setTime(0);
                classes.putNextEntry(descriptor);
                classes.write(descriptorContents.getBytes(StandardCharsets.UTF_8));
                classes.closeEntry();
            }
            if (includeConfiguration) {
                JarEntry configuration = new JarEntry("FoundryJava.foundryextension");
                configuration.setTime(0);
                classes.putNextEntry(configuration);
                classes.write(BINDING_CONFIGURATION);
                classes.closeEntry();
            }
        }
        return output.toByteArray();
    }

    private static void writeRawZip(Path output, List<RawZipEntry> entries) throws IOException {
        ByteArrayOutputStream archive = new ByteArrayOutputStream();
        List<Integer> offsets = new ArrayList<>();
        List<Long> checksums = new ArrayList<>();
        for (RawZipEntry entry : entries) {
            offsets.add(archive.size());
            CRC32 checksum = new CRC32();
            checksum.update(entry.contents());
            checksums.add(checksum.getValue());
            byte[] name = entry.name().getBytes(StandardCharsets.UTF_8);
            writeLittleEndian(archive, 0x04034b50, 4);
            writeLittleEndian(archive, 20, 2);
            writeLittleEndian(archive, 0, 2);
            writeLittleEndian(archive, 0, 2);
            writeLittleEndian(archive, 0, 2);
            writeLittleEndian(archive, 0, 2);
            writeLittleEndian(archive, checksum.getValue(), 4);
            writeLittleEndian(archive, entry.contents().length, 4);
            writeLittleEndian(archive, entry.contents().length, 4);
            writeLittleEndian(archive, name.length, 2);
            writeLittleEndian(archive, 0, 2);
            archive.write(name);
            archive.write(entry.contents());
        }
        int centralDirectoryOffset = archive.size();
        for (int index = 0; index < entries.size(); index++) {
            RawZipEntry entry = entries.get(index);
            byte[] name = entry.name().getBytes(StandardCharsets.UTF_8);
            writeLittleEndian(archive, 0x02014b50, 4);
            writeLittleEndian(archive, 20, 2);
            writeLittleEndian(archive, 20, 2);
            writeLittleEndian(archive, 0, 2);
            writeLittleEndian(archive, 0, 2);
            writeLittleEndian(archive, 0, 2);
            writeLittleEndian(archive, 0, 2);
            writeLittleEndian(archive, checksums.get(index), 4);
            writeLittleEndian(archive, entry.contents().length, 4);
            writeLittleEndian(archive, entry.contents().length, 4);
            writeLittleEndian(archive, name.length, 2);
            writeLittleEndian(archive, 0, 2);
            writeLittleEndian(archive, 0, 2);
            writeLittleEndian(archive, 0, 2);
            writeLittleEndian(archive, 0, 2);
            writeLittleEndian(archive, 0, 4);
            writeLittleEndian(archive, offsets.get(index), 4);
            archive.write(name);
        }
        int centralDirectorySize = archive.size() - centralDirectoryOffset;
        writeLittleEndian(archive, 0x06054b50, 4);
        writeLittleEndian(archive, 0, 2);
        writeLittleEndian(archive, 0, 2);
        writeLittleEndian(archive, entries.size(), 2);
        writeLittleEndian(archive, entries.size(), 2);
        writeLittleEndian(archive, centralDirectorySize, 4);
        writeLittleEndian(archive, centralDirectoryOffset, 4);
        writeLittleEndian(archive, 0, 2);
        Files.write(output, archive.toByteArray());
    }

    private static void writeLittleEndian(ByteArrayOutputStream output, long value, int byteCount) {
        for (int index = 0; index < byteCount; index++) {
            output.write((int) (value >>> (index * 8)) & 0xff);
        }
    }

    private void publishModule(
            Path repository, String module, String registry, List<String> dependencies)
            throws IOException {
        Path version = repository.resolve("games/cafecito/test/" + module + "/1");
        Files.createDirectories(version);
        moduleJar(version.resolve(module + "-1.jar"), module, registry);
        String dependencyXml =
                dependencies.stream()
                        .map(
                                coordinate -> {
                                    String[] parts = coordinate.split(":");
                                    return """
                                            <dependency>
                                              <groupId>%s</groupId>
                                              <artifactId>%s</artifactId>
                                              <version>%s</version>
                                            </dependency>
                                            """
                                            .formatted(parts[0], parts[1], parts[2]);
                                })
                        .reduce((left, right) -> left + right)
                        .orElse("");
        Files.writeString(
                version.resolve(module + "-1.pom"),
                """
                <project xmlns="http://maven.apache.org/POM/4.0.0">
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>games.cafecito.test</groupId>
                  <artifactId>%s</artifactId>
                  <version>1</version>
                  <dependencies>
                %s
                  </dependencies>
                </project>
                """
                        .formatted(module, dependencyXml));
    }

    private String descriptor(String module, String registry) {
        return """
                format=2
                module=%s
                registry=%s
                api_sha256=%s
                generator_version=1
                runtime_contract_version=1
                bridge_contract_version=1
                class=example.Extension|Extension|example.Node|SCENE|
                """
                .formatted(module, registry, API_SHA);
    }

    private record MavenDependency(String group, String artifact, String version, String scope) {}

    private record RawZipEntry(String name, byte[] contents) {}
}
